# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cf9fe101dd938952e237a49a8d4fda71f34b60cb44383febee8b7d684e1bd00e645b6fba964d12b71fbd1ce525863c27c96cf63c26e90034d7dee45f069e41e6

test:
  secret_key_base: 6926ab70c019f948b78f69b1d034915564e9e2b428aad83fc4c0341aa7437df04f0b081ccb59024e423bf75b09332588559ba94b6d836b5ca7a29ee5cea847ea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
